version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: anesp
      POSTGRES_USER: anesp
      POSTGRES_PASSWORD: anesp
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: npm run dev
    working_dir: /app
    environment:
      PORT: 5000
      DATABASE_CLIENT: postgres
      DATABASE_URL: postgres://anesp:anesp@db:5432/anesp
      JWT_SECRET: please-change-me
      EMAIL_HOST: smtp.example.com
      EMAIL_PORT: 587
      EMAIL_USER: no-reply@anesp.gov.mr
      EMAIL_PASSWORD: change-me
      UPLOAD_DIR: uploads
      PDF_OUTPUT_DIR: generated_docs
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    working_dir: /app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
